version: '3,3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=blogWebsite
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - 3309:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 4001:80
    environment:
      - PMA_ARBITRARY=1